tasks:
  - command: "pip install -r requirements"
  - command: "pip install -e ."
  - command: "jupyter lab --ip=0.0.0.0 --port=8888 --NotebookApp.token='' &"
# Ports to expose on workspace startup
#ports:
#  - port: 8888
